hut_meal/urls.py
from tkinter.font import names

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from hut_meal import settings
from hut_meal.views import home_page, header, footer
from hut_meal_about.views import about_us
from hut_meal_blog.views import latest_posts
from hut_meal_brand.views import render_brand_list
from hut_meal_category.views import list_blog_categories, list_product_categories
from hut_meal_product.views import special_products
from hut_meal_tag.views import list_tags

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page),
    path('header/', header, name='header'),
    path('footer/', footer, name='footer'),
    path('', include('hut_meal_product.urls', namespace='product')),
    path('', include('hut_meal_brand.urls', namespace='brand')),
    path('render-brand-list/', render_brand_list, name='render_brand_list'),
    path('', include('hut_meal_profile.urls', namespace='profile')),
    path('', include('hut_meal_reservation.urls', namespace='reservation')),
    path('', include('hut_meal_order.urls', namespace='order')),
    path('special_products/', special_products, name= 'special_products'),
    path('latest_post/', latest_posts, name= 'latest_posts'),

    path('', include('hut_meal_blog.urls', namespace='blog')),
    path('', include('hut_meal_menu.urls', namespace='menu')),
    path('', include('hut_meal_Team.urls', namespace='team')),
    path('about-us', about_us, name='about_us'),

    path('', include('hut_meal_contact.urls', namespace='contact')),
    path('list_tags', list_tags, name = 'list_tags'),
    path('list-blog-categories', list_blog_categories, name = 'list_blog_categories'),
    path('list-product-categories', list_product_categories, name = 'list_product_categories'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hut_meal_contact/urls.py
from django.urls import path

from .views import contact_us

app_name = 'hut_meal_contact'

urlpatterns = [
    path('contact-us', contact_us, name='contact_us')
]

hut_meal_contact/models.py
from django.db import models

# Create your models here.




class Contact(models.Model):
    name = models.CharField(max_length=40)
    phone = models.CharField(max_length=13)
    email = models.EmailField(max_length=120)
    message = models.TextField()
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Contacts'

hut_meal_contact/forms.py
from django import forms
from django.core import validators

from hut_meal_contact.models import Contact


class ContactUsForm(forms.ModelForm):
    name = forms.CharField(
        label='نام کامل',
        widget=forms.TextInput(attrs={'class': 'input-text', "placeholder": "enter your fullname", "type":"text", 'maxlength': '20'}))

    email = forms.EmailField(
        label='ایمیل',
        widget=forms.EmailInput(attrs={'class': 'input-text', "placeholder": "enter your email"}))

    phone = forms.CharField(
        widget=forms.TextInput(attrs={"class": "input-text validate-email", "placeholder": "enter your phone", "type": "text"}),
        validators=[
            validators.MaxLengthValidator(limit_value=11, message="نام کاربری نباید بیش از 11 کاراکتر باشد ")])

    message = forms.CharField(
        label='پیام شما',
        widget=forms.Textarea(attrs={'class': 'required-entry input-text', "cols":"5", "rows":"3", "title":"Comment", "name":"comment"}))

    class Meta:
        model = Contact
        fields = ('name', 'email','phone', 'message')

hut_meal_contact/views.py
from django.contrib import messages
from django.shortcuts import render

from hut_meal_contact.forms import ContactUsForm
from hut_meal_contact.models import Contact
from hut_meal_setting.models import HomePageSettings


# Create your views here.



def contact_us(request):
    setting = HomePageSettings.objects.first()
    contact_form = ContactUsForm(data=request.POST or None)
    if contact_form.is_valid():
        contact_form.save()
        messages.info(request, 'Your message was sent successfully.')
    context = {'setting': setting}
    return render(request, 'contact-us.html', context)

hut_meal_contact/templates/contact-us.html
{% extends 'base/base.html' %}
{% load render_partial %}
{% load static %}
{% block contents %}
    <!--// SubHeader \\-->
    <div class="hotmeal-subheader-map">
        <div id="map"></div>
    </div>
    <!--// SubHeader \\-->

    <!--// Main Content \\-->
    <div class="hotmeal-main-content hotmeal-contact-padding">

        <!--// Main Section \\-->
        <div class="hotmeal-main-section hotmeal-contact-full">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="hotmeal-contact-us">
                            <div class="hotmeal-contact-info">
                                <ul>
                                    <li>
                                        <div class="hotmeal-contact-info-wrap">
                                            <i class="icon hotmeal-telephone"></i>
                                            <small></small>
                                            <h5>Call Us At</h5>
                                            <p>{{ setting.phone }}</p>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="hotmeal-contact-info-wrap">
                                            <i class="icon hotmeal-close-envelope"></i>
                                            <small></small>
                                            <h5>Mail Us At</h5>
                                            <a href="mailto:yourdomain@name.com">{{ setting.email }}</a>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="hotmeal-contact-info-wrap">
                                            <i class="icon hotmeal-facebook-placeholder-for-locate-places-on-maps"></i>
                                            <small></small>
                                            <h5>Meet Us At</h5>
                                            <p>{{ setting.address }}</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="hotmeal-contact-form">
                                <form method="post" action="{% url 'contact:contact_us' %}">
                                    {% csrf_token %}
                                    <ul>
                                        <li>
                                            <input value="Name*" name="name"
                                                   onblur="if(this.value == '') { this.value ='Name*'; }"
                                                   onfocus="if(this.value =='Name*') { this.value = ''; }" tabindex="0"
                                                   type="text">
                                        </li>
                                        <li>
                                            <input value="Phone*" name="phone"
                                                   onblur="if(this.value == '') { this.value ='Phone*'; }"
                                                   onfocus="if(this.value =='Phone*') { this.value = ''; }" tabindex="0"
                                                   type="text">
                                        </li>
                                        <li>
                                            <input value="Email" name="email"
                                                   onblur="if(this.value == '') { this.value ='Email'; }"
                                                   onfocus="if(this.value =='Email') { this.value = ''; }" tabindex="0"
                                                   type="email">
                                        </li>
                                        <li class="full">
                                            <textarea placeholder="Messege*" name="message"></textarea>
                                        </li>
                                        <li class="full">
                                            <label>
                                                <input type="submit" name="submit" value="Send Now">
                                                <small></small>
                                            </label>
                                            <span class="output_message"></span>
                                        </li>
                                    </ul>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--// Main Section \\-->

        <!--// Main Section \\-->
        {% render_partial 'render_brand_list' %}
        <!--// Main Section \\-->

    </div>
    <!--// Main Content \\-->
{% endblock %}