hut_meal/urls.py
from tkinter.font import names

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from hut_meal import settings
from hut_meal.views import home_page, header, footer
from hut_meal_about.views import about_us
from hut_meal_blog.views import latest_posts
from hut_meal_brand.views import render_brand_list
from hut_meal_category.views import list_blog_categories, list_product_categories
from hut_meal_product.views import special_products
from hut_meal_tag.views import list_tags

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page),
    path('header/', header, name='header'),
    path('footer/', footer, name='footer'),
    path('', include('hut_meal_product.urls', namespace='product')),
    path('', include('hut_meal_brand.urls', namespace='brand')),
    path('render-brand-list/', render_brand_list, name='render_brand_list'),
    path('', include('hut_meal_profile.urls', namespace='profile')),
    path('', include('hut_meal_reservation.urls', namespace='reservation')),
    path('', include('hut_meal_order.urls', namespace='order')),
    path('special_products/', special_products, name= 'special_products'),
    path('latest_post/', latest_posts, name= 'latest_posts'),

    path('', include('hut_meal_blog.urls', namespace='blog')),
    path('', include('hut_meal_menu.urls', namespace='menu')),
    path('', include('hut_meal_Team.urls', namespace='team')),
    path('about-us', about_us, name='about_us'),

    path('', include('hut_meal_contact.urls', namespace='contact')),
    path('list_tags', list_tags, name = 'list_tags'),
    path('list-blog-categories', list_blog_categories, name = 'list_blog_categories'),
    path('list-product-categories', list_product_categories, name = 'list_product_categories'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hut_meal_order/urls.py
from django.urls import path

from .views import cart_page, add_new_item_order, remove_cart_item, send_request, verify

app_name = 'hut_meal_order'

urlpatterns = [
    path('cart-page', cart_page, name='cart_page'),
    # path('account/order/', order, name='order'),
    # path('account/order/order-detail/<order_id>', order_detail, name='order_details'),
    path('add-naw-item-order/<product_id>', add_new_item_order, name='add_new_item_order'),
    path('remove-cart-item/<product_id>', remove_cart_item),
    path('request/<id>/<letter>', send_request, name='request'),
    path('verify/<id>/<letter>', verify, name='verify'),
]

hut_meal_product/urls.py
from django.urls import path

from .views import ProductListView, product_detail, ProductListView2, SearchProducts

app_name = 'hut_meal_product'

urlpatterns = [
    path('products-list1', ProductListView.as_view(), name='products_list1'),
    path('products-list2', ProductListView2.as_view(), name='products_list2'),
    path('products/<int:product_id>/<title>/', product_detail, name='product_detail'),
    path('products/search/', SearchProducts.as_view(), name='product_search'),
]

hut_meal_product/models.py
import os
import random

from django.db import models
from django.db.models import Q

from hut_meal_brand.models import ProductBrand
from hut_meal_category.models import ProductCategory


# from store_brand.models import ProductBrand
# from store_products_category.models import ProductCategory


# Create your models here.


def get_file_extension(file):
    base_name = os.path.basename(file)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image(instance, filename):
    rand_name = random.randint(1, 999999999999999)
    name, ext = get_file_extension(filename)
    file_name = f"{instance.id}-{rand_name}{ext}"
    return f"products/{file_name}"

def upload_image_gallery(instance, filename):
    rand_name = random.randint(1, 999999999999999)
    name, ext = get_file_extension(filename)
    file_name = f"{instance.id}-{rand_name}{ext}"
    return f"gallery/{file_name}"


class ProductDiscount(models.Model):
    title = models.CharField(max_length=50, verbose_name='عنوان تخفیف')
    percentage = models.IntegerField( verbose_name='درصد تخفیف %')


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'تخیف'
        verbose_name_plural = 'تخفیف ها'

class ProductSize(models.Model):
    title = models.CharField(max_length=50, verbose_name='عنوان سایز')
    def __str__(self):
        return self.title
    class Meta:
        verbose_name = 'سایز'
        verbose_name_plural = 'سایز ها'


class ProductColor(models.Model):
    title = models.CharField(max_length=100, verbose_name='عنوان رنگ')
    image_code = models.CharField(max_length=100, verbose_name='کد رنگ')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'رنگ'
        verbose_name_plural = 'رنگ ها'


class ProductManager(models.Manager):
    def get_product_by_id(self, productid):
        qs = self.get_queryset().filter(id=productid, active=True)
        if qs.count() == 1:
            return qs.first()
        return None

    def get_active_product(self):
        return self.get_queryset().filter(active=True)


    def search_products(self, query):
        lookup = Q(title__icontains=query) | Q(description__icontains=query) | Q(tag__title__icontains=query) | Q(categories__title__icontains=query)
        return self.get_queryset().filter(lookup, active=True).distinct()

    def get_product_by_category(self, category_name):
        return self.get_queryset().filter(categories__name__iexact=category_name, active=True)

    def get_product_by_brand(self, brand_name):
        return self.get_queryset().filter(brand__name__iexact=brand_name, active=True)


class Product(models.Model):
    title = models.CharField(max_length=150, verbose_name="عنوان")
    description = models.TextField(verbose_name="توضیحات")
    #    slug = models.SlugField(blank=True, unique=True)
    price = models.DecimalField(max_digits=15, decimal_places=0, verbose_name="قیمت")
    image = models.ImageField(upload_to=upload_image, null=True, blank=True, verbose_name="تصویر")
    active = models.BooleanField(default=False, verbose_name="فعال/غیرفعال")
    time = models.DateTimeField(auto_now_add=True)
    categories = models.ManyToManyField(ProductCategory, blank=True, verbose_name='دسته بندی')
    color = models.ManyToManyField(ProductColor, blank=True, verbose_name='رنگ')
    size = models.ManyToManyField(ProductSize, blank=True, verbose_name='سایز')
    brand = models.ForeignKey(ProductBrand, on_delete=models.CASCADE, verbose_name='برند')
    featured = models.BooleanField(default=False, verbose_name='محصول ویژه')
    visits = models.IntegerField(default=0, verbose_name='تعداد مشاهده')
    discount = models.ForeignKey(ProductDiscount, on_delete=models.CASCADE, verbose_name='درصد تخفیف %')

    objects = ProductManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def get_product_detail_url(self):
        return f"/products/{self.id}/{self.title.replace(' ', '-')}"

    def price2(self):
        price2 = (self.price) - (self.price) * (self.discount.percentage) / 100
        return price2





class ProductGallery(models.Model):
    title = models.CharField(max_length=100, verbose_name='عنوان')
    image = models.ImageField(upload_to=upload_image_gallery, null=True, blank=True, verbose_name="تصویر")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='انتخاب محصول')

    class Meta:
        verbose_name = 'تصویر'
        verbose_name_plural='گالری تصاویر'

    def __str__(self):
        return self.title

hut_meal_product/views.py
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.views.generic.list import ListView
from django.shortcuts import render, redirect

from hut_meal_comment.forms import CommentProductForm
from hut_meal_comment.models import CommentProduct
from hut_meal_product.models import Product, ProductGallery, ProductSize, ProductColor


# Create your views here.





class ProductListView(ListView):
    template_name = 'product_list1.html'
    paginate_by = 4
    def get_queryset(self):
        return Product.objects.get_active_product()


class ProductListView2(ProductListView):
    template_name = 'product_list2.html'
    paginate_by = 6


def product_detail(request, *args, **kwargs):
    get_product_id = kwargs['product_id']
    # new_order_form = UserNewOrderForm(request.POST or None, initial=({'product_id': get_product_id}))
    # tag_form = TagForm(request.POST or None)
    product = Product.objects.get_product_by_id(get_product_id)
    related_products = Product.objects.get_queryset().filter(categories__product=product).distinct()[:3]
    comment_form = CommentProductForm(request.POST or None)
    comments = product.comment_products.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentProductForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.product = product
            new_comment.save()
            return HttpResponseRedirect(request.path_info)

    if product is None:
        raise Http404('محصول مورد نظر یافت نشد!')
    product.visits += 1
    product.save()

    gallery = ProductGallery.objects.filter(product_id=get_product_id)
    size = ProductSize.objects.filter(product=product)
    color = ProductColor.objects.filter(product=product)

    # tag = product.tag_set.all()

    context = {
        'product': product,
        'gallery': gallery,
        'size': size,
        'color': color,
        'comments': comments,
        'comment_form': comment_form,
        'related_products': related_products,
        # 'tag': tag,
        # 'tag_form': tag_form,
        # 'new_order_form':new_order_form
    }
    return render(request, 'product_detail.html', context)


class SearchProducts(ListView):
    template_name = 'product_list2.html'
    paginate_by = 10
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query is not None:
            return Product.objects.search_products(query)
        return Product.objects.get_active_product()


def special_products(request):
    products = Product.objects.filter(featured=True)[:4]
    context= {'products': products}
    return render(request,'speial_products.html', context)

hut_meal_product/templates/product_item_component.html
<li class="col-md-4">
    <figure><span>sale</span><a href="{{ product.get_product_detail_url }}"><img src="{{ product.image.url }}"
                                                                                 alt=""></a>
        <figcaption>
            <a href="shop-detail.html"><i class="icon hotmeal-link"></i> <span class="btn-shape"></span></a>
            <a href="{% url 'order:add_new_item_order' product.id %}"><i class="fa fa-shopping-bag"></i> <span class="btn-shape"></span></a>
        </figcaption>
    </figure>
    <div class="hotmeal-shop-grid-text">
        <h2><a href="{{ product.get_product_detail_url }}">{{ product.title }}</a></h2>
        <div class="star-rating"><span class="star-rating-box" style="width:60%"></span></div>
        <small>( 2 Reviews )</small>
        {% if product.discount.percentage > 0 %}
            <span> $ {{ product.price2 }}
                <del> $ {{ product.price }}</del></span>
        {% else %}
            <span> $ {{ product.price }}</span>
        {% endif %}
    </div>
</li>

hut_meal_product/templates/product_list.html
{% extends 'base/base.html' %}
{% load render_partial %}
{% block contents %}
    {% load static %}

    <!--// SubHeader \\-->
    <div class="hotmeal-subheader">
        <span class="hotmeal-subheader-transparent"></span>
        <div class="hotmeal-subheader-text">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <span>Shop</span>
                        {% block page_title %}{% endblock %}
                        <p>Sed vulputate elementum aliquam. Nunc vel efficitur ante. Ut gravida nulla id ornare
                            sodales.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="hotmeal-breadcrumb">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <ul>
                            <li><a href="index-2.html">Homepage</a></li>
                            <li class="active">Shop List W/L/Sidebar</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--// SubHeader \\-->

    <!--// Main Content \\-->
    <div class="hotmeal-main-content">

        <!--// Main Section \\-->
        <div class="hotmeal-main-section">
            <div class="container">
                <div class="row">

                    <!--// Sidebar \\-->
                    <aside class="col-md-3">

                        <!--// Widget Search \\-->
                        <div class="widget widget_search">
                            <form id="mob-search" name="search" action="{% url 'product:product_search' %}"
                                  method="get">
                                <input type="text" name="q" placeholder="Search ..." value="{{ request.GET.q }}"
                                       onblur="if(this.value == '') { this.value ='Type Your Keyword'; }"
                                       onfocus="if(this.value =='Type Your Keyword') { this.value = ''; }">
                                <label><input type="submit" value=""></label>
                            </form>
                        </div>
                        <!--// Widget Search \\-->

                        <!--// Widget Popular Post \\-->
                        {% render_partial 'latest_posts' %}
                        <!--// Widget Popular Post \\-->
                        {% render_partial 'list_tags' %}
                        <!--// Widget Cetagories \\-->
                        {% render_partial 'list_product_categories' %}
                        <!--// Widget Cetagories \\-->

                        <!--// Widget Best Deals \\-->
                        {% render_partial 'special_products' %}
                        <!--// Widget Best Deals \\-->

                        <!--// Widget Calendar Archives \\-->
                        <div class="widget widget_cetagories">
                            <h2 class="widget-heading">Calendar Archives</h2>
                            <ul>
                                <li><a href="404.html">December <span>(12)</span></a></li>
                                <li><a href="404.html">January <span>(09)</span></a></li>
                                <li><a href="404.html">March <span>(17)</span></a></li>
                                <li><a href="404.html">May <span>(08)</span></a></li>
                                <li><a href="404.html">August <span>(05)</span></a></li>
                                <li><a href="404.html">September <span>(05)</span></a></li>
                            </ul>
                        </div>
                        <!--// Widget Calendar Archives \\-->

                    </aside>
                    <!--// Sidebar \\-->

                    <div class="col-md-9">
                        <div class="hotmeal-shop-filter">
                            <span>Showing 1-6 of 30 Results</span>
                            <!-- Nav tabs -->
                            <ul class="nav-tabs" role="tablist">
                                <li role="presentation" class="active"><a href="#home"
                                                                          aria-controls="home"
                                                                          role="tab"
                                                                          data-toggle="tab"
                                ><i
                                        class="icon hotmeal-signs22"></i> <span>List</span></a></li>
                                <li role="presentation"><a href="#profile"
                                                           aria-controls="profile"
                                                           role="tab"
                                                           data-toggle="tab"
                                ><i class="icon hotmeal-squares2"></i>
                                    <span>Grid</span></a></li>
                            </ul>
                            <!-- Tab panes -->
                            <form>
                                <div class="hotmeal-filter-select">
                                    <select>
                                        <option value="Default Sorting">Default Sorting</option>
                                        <option value="Default Sorting">Default Sorting</option>
                                        <option value="Default Sorting">Default Sorting</option>
                                        <option value="Default Sorting">Default Sorting</option>
                                    </select>
                                </div>
                            </form>
                        </div>
                        {% block product_item %}

                        {% endblock %}
                        <!--// Pagination \\-->
                        <div class="hotmeal-pagination">
                            <ul class="page-numbers">
                                {% if page_obj.has_previous %}
                                    <li><a class="previous page-numbers"
                                           href="?page={{ page_obj.previous_page_number }}"><span
                                            aria-label="Next"><i
                                            class="fa fa-angle-left"></i></span> <small
                                            class="btn-shape"></small></a>
                                    </li>
                                {% endif %}
                                {% for page in paginator.page_range %}
                                    {% if page == page_obj.number %}
                                        <li class="active"><a class="page-numbers"
                                                              href="?page={{ page }}">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?page={{ page }}">{{ page }} <small
                                                class="btn-shape"></small></a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li><a class="next page-numbers"
                                           href="?page={{ page_obj.next_page_number }}"><span
                                            aria-label="Next"><i
                                            class="fa fa-angle-right"></i></span> <small
                                            class="btn-shape"></small></a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                        <!--// Pagination \\-->
                    </div>
                    <div role="tabpanel" class="tab-pane" id="profile">
                        <div class="hotmeal-shop hotmeal-shop-grid">
                            <ul class="row">
                                {% for product in page_obj %}
                                    {% include 'product_item_component.html' with product=product %}
                                {% endfor %}
                            </ul>
                        </div>
                        <!--// Pagination \\-->
                        <div class="hotmeal-pagination">
                            <ul class="page-numbers">
                                {% if page_obj.has_previous %}
                                    <li><a class="previous page-numbers"
                                           href="?page={{ page_obj.previous_page_number }}"><span
                                            aria-label="Next"><i
                                            class="fa fa-angle-left"></i></span> <small
                                            class="btn-shape"></small></a>
                                    </li>
                                {% endif %}
                                {% for page in paginator.page_range %}
                                    {% if page == page_obj.number %}
                                        <li class="active"><a class="page-numbers"
                                                              href="?page={{ page }}">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?page={{ page }}">{{ page }} <small
                                                class="btn-shape"></small></a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li><a class="next page-numbers"
                                           href="?page={{ page_obj.next_page_number }}"><span
                                            aria-label="Next"><i
                                            class="fa fa-angle-right"></i></span> <small
                                            class="btn-shape"></small></a>
                                    </li>
                                {% endif %}
                            </ul>
                        </div>
                        <!--// Pagination \\-->
                    </div>
                </div>
            </div>

        </div>
    </div>
    </div>
    <!--// Main Section \\-->

    </div>
    <!--// Main Content \\-->

{% endblock %}

hut_meal_product/templates/product_list1.html
{% extends 'product_list.html' %}
{% block page_product_title %}<h1>Shop List</h1>{% endblock %}
{% block product_item %}
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">
            <div class="hotmeal-shop hotmeal-shop-list">
                <ul class="row">
                    {% for product in page_obj %}
                        <li class="col-md-12">
                            <figure><a href="{{ product.get_product_detail_url }}"><img
                                    src="{{ product.image.url }}"
                                    alt=""><span
                                    class="hover-btn"><i
                                    class="icon hotmeal-link"></i><small></small></span></a>
                            </figure>
                            <div class="hotmeal-shop-list-text">
                                <h2>
                                    <a href="{{ product.get_product_detail_url }}">{{ product.title }}</a>
                                </h2>
                                <div class="star-rating"><span class="star-rating-box"
                                                               style="width:60%"></span></div>
                                <small>( 2 Reviews )</small>
                                {% if product.discount.percentage > 0 %}
                                    <span> $ {{ product.price2 }}
                                                                    <del> $ {{ product.price }}</del></span>
                                {% else %}
                                    <span> $ {{ product.price }}</span>
                                {% endif %}
                                <p>{{ product.description|truncatechars:250 }}</p>
                                <a href="{% url 'order:add_new_item_order' product.id %}"
                                   class="hotmeal-learn-btn">Add To Cart
                                    <span
                                            class="btn-shape"></span></a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
{% endblock %}

hut_meal_product/templates/product_list2.html
{% extends 'product_list.html' %}
{% block page_product_title %}<h1>Shop gird</h1>{% endblock %}
{% block product_item %}
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">
            <div class="hotmeal-shop hotmeal-shop-grid">
                <ul class="row">
                    {% for product in page_obj %}
                        <li class="col-md-4">
                            <figure><span>sale</span><a href="{{ product.get_product_detail_url }}"><img
                                    src="{{ product.image.url }}" alt=""></a>
                                <figcaption>
                                    <a href="shop-detail.html"><i class="icon hotmeal-link"></i> <span
                                            class="btn-shape"></span></a>
                                    <a href="shop-detail.html"><i class="fa fa-shopping-bag"></i> <span
                                            class="btn-shape"></span></a>
                                </figcaption>
                            </figure>
                            <div class="hotmeal-shop-grid-text">
                                <h2><a href="{{ product.get_product_detail_url }}">{{ product.title }}</a></h2>
                                <div class="star-rating"><span class="star-rating-box" style="width:60%"></span></div>
                                <small>( 2 Reviews )</small>
                                <span>$ 25.00 <del>$ 30.00</del></span>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
{% endblock %}

hut_meal_product/templates/speial_products.html
<div class="widget widget_deals">
    <h2 class="widget-heading">Best Deals</h2>
    <ul>
        {% for product in products %}
        <li>
            <figure><a href="{{ product.get_product_detail_url }}"><img
                    src="{{ product.image.url }}" alt=""></a>
            </figure>
            <div class="widget-deals-text">
                <h6><a href="{{ product.get_product_detail_url }}">{{ product.title }}</a></h6>
                <span>{{ product.price2 }}</span>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>