hut_meal/urls.py
from tkinter.font import names

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from hut_meal import settings
from hut_meal.views import home_page, header, footer
from hut_meal_about.views import about_us
from hut_meal_blog.views import latest_posts
from hut_meal_brand.views import render_brand_list
from hut_meal_category.views import list_blog_categories, list_product_categories
from hut_meal_product.views import special_products
from hut_meal_tag.views import list_tags

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page),
    path('header/', header, name='header'),
    path('footer/', footer, name='footer'),
    path('', include('hut_meal_product.urls', namespace='product')),
    path('', include('hut_meal_brand.urls', namespace='brand')),
    path('render-brand-list/', render_brand_list, name='render_brand_list'),
    path('', include('hut_meal_profile.urls', namespace='profile')),
    path('', include('hut_meal_reservation.urls', namespace='reservation')),
    path('', include('hut_meal_order.urls', namespace='order')),
    path('special_products/', special_products, name= 'special_products'),
    path('latest_post/', latest_posts, name= 'latest_posts'),

    path('', include('hut_meal_blog.urls', namespace='blog')),
    path('', include('hut_meal_menu.urls', namespace='menu')),
    path('', include('hut_meal_Team.urls', namespace='team')),
    path('about-us', about_us, name='about_us'),

    path('', include('hut_meal_contact.urls', namespace='contact')),
    path('list_tags', list_tags, name = 'list_tags'),
    path('list-blog-categories', list_blog_categories, name = 'list_blog_categories'),
    path('list-product-categories', list_product_categories, name = 'list_product_categories'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hut_meal_order/urls.py
from django.urls import path

from .views import cart_page, add_new_item_order, remove_cart_item, send_request, verify

app_name = 'hut_meal_order'

urlpatterns = [
    path('cart-page', cart_page, name='cart_page'),
    # path('account/order/', order, name='order'),
    # path('account/order/order-detail/<order_id>', order_detail, name='order_details'),
    path('add-naw-item-order/<product_id>', add_new_item_order, name='add_new_item_order'),
    path('remove-cart-item/<product_id>', remove_cart_item),
    path('request/<id>/<letter>', send_request, name='request'),
    path('verify/<id>/<letter>', verify, name='verify'),
]

hut_meal_profile/urls.py
from django.urls import path

from .views import login_page, register_page, log_out_page, account_main_page

app_name = 'hut_meal_profile'

urlpatterns = [
    path('login/', login_page, name='login_page'),
    path('account', account_main_page, name='account_main_page'),
    path('register-page', register_page, name='register_page'),
    path('log-out-age', log_out_page, name='log_out_page'),
]

hut_meal_profile/models.py
from django.db import models

# Create your models here.

hut_meal_profile/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core import validators


class LoginForm(forms.Form):
    username = forms.CharField(
        widget= forms.TextInput(attrs={"type":"text", "placeholder":"enter your username"})
    )
    password = forms.CharField(
        widget= forms.PasswordInput(attrs={"type":"text", "placeholder":"enter your password"})
    )




User = get_user_model()
class UserAccountForm(forms.Form):
    first_name = forms.CharField(
        widget= forms.TextInput(attrs={"type":"text", "placeholder":"Enter your name."})
    )
    last_name = forms.CharField(
        widget= forms.TextInput(attrs={"type":"text", "placeholder":"Enter your last name."})
    )
    username = forms.CharField(
        widget=forms.TextInput(attrs={"type":"text", "placeholder": "enter your username"}),
        validators=[
            validators.MaxLengthValidator(limit_value=20, message="نام کاربری نباید بیش از 20 کاراکتر باشد ")
        ])
    email = forms.EmailField(
        widget=forms.TextInput(attrs={"type":"email", "placeholder": "enter your email"}),
        validators=[
            validators.EmailValidator("ایمیل نامعتبر است !")
        ])

    phone = forms.CharField(

        widget=forms.TextInput(attrs={"type":"text", "placeholder": "enter your phone"}),
        validators=[
            validators.MaxLengthValidator(limit_value=11, message="نام کاربری نباید بیش از 11 کاراکتر باشد ")
        ])

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"type":"text", "placeholder": "enter your password"}))
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={"type":"text", "placeholder": "re enter your password"}))
    address = forms.CharField(
        widget=forms.TextInput(attrs={"class":"full-form", 'placeholder': 'enter your address'})
    )
    company = forms.CharField(
        widget=forms.TextInput(attrs={"type":"text", 'placeholder': 'enter your Company'})
    )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not "gmail.com" in email:
            raise forms.ValidationError("Email must contain a gmail address")
        return email

    def clean(self):
        data = self.cleaned_data
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")

        if password != password2:
            raise forms.ValidationError("Passwords must match")
        return data

hut_meal_profile/views.py
from django.contrib.auth import authenticate, login, get_user_model, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from hut_meal_profile.forms import LoginForm, UserAccountForm
from hut_meal_user.models import UserModel
from django.contrib.auth.decorators import login_required
from django.http import Http404
# Create your views here.



def login_page(request):
    login_form = LoginForm(request.POST or None)
    if login_form.is_valid():
        username = login_form.cleaned_data.get('username')
        password = login_form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.info(request, 'Login successfully completed.')
            return redirect("/")
        else:
            messages.info(request, 'The username or password is incorrect.')
    context = {
        "login_form": login_form
    }
    return render(request, "login.html", context)






@login_required(login_url='/login')
def account_main_page(request):
    context = {}
    return render(request, 'account.html', context)






User = get_user_model()
def register_page(request):
    if 'email' in request.POST:
        email = request.POST['email']
        first_name = request.POST['first_name']
        register_form = UserAccountForm(request.POST or None,initial={'email': email, 'first_name':first_name})
    context = {}
    if request.user.is_authenticated :
        user_id = request.user.id
        user = User.objects.get(id=user_id)
        if user is None:
            raise Http404()
        register_form = UserAccountForm(request.POST or None,
                                    initial={'first_name': user.first_name, 'last_name': user.last_name,
                                             'phone': user.usermodel.phone, 'username': user.username,
                                             'email': user.email, 'address': user.usermodel.address,
                                             'company': user.usermodel.company})
        context['user']= user
    else:
        register_form = UserAccountForm(request.POST or None)
    if register_form.is_valid():
        username = register_form.cleaned_data.get('username')
        email = register_form.cleaned_data.get('email')
        password = register_form.cleaned_data['password']
        first_name = register_form.cleaned_data.get('first_name')
        last_name = register_form.cleaned_data.get('last_name')
        phone = register_form.cleaned_data.get('phone')
        address = register_form.cleaned_data.get('address')
        company = register_form.cleaned_data.get('company')
        user_obj = User.objects.filter(username=username).first()
        if user_obj is not None and user_obj.check_password(password):
            messages.info(request, 'The username or password is incorrect.')
            return redirect('/')
        else:
            new_user = User.objects.create_user(username=username, email=email, password=password,
                                                first_name=first_name, last_name=last_name)

            UserModel.objects.create(user_id=new_user.id, phone=phone, address=address, company=company)
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("/")

    context["register_form"]= register_form
    return render(request, "register.html", context)




def log_out_page(request):
    logout(request)
    return redirect('/login-page')

hut_meal_profile/templates/account.html
{% extends 'base/base.html' %}
{% block contents %}
    {% load static %}

    <!--// SubHeader \\-->
    <div class="hotmeal-subheader">
        <span class="hotmeal-subheader-transparent"></span>
        <div class="hotmeal-subheader-text">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <span>account</span>
                        <h1>account</h1>
                        <p>Sed vulputate elementum aliquam. Nunc vel efficitur ante. Ut gravida nulla id ornare
                            sodales.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="hotmeal-breadcrumb">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <ul>
                            <li><a href="index-2.html">Homepage</a></li>
                            <li class="active">account</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--// SubHeader \\-->

    <!--// Main Content \\-->
    <div class="hotmeal-main-content">

        <!--// Main Section \\-->
        <div class="hotmeal-main-section hotmeal-breakfastfull">
            <div class="container">
                <div class="row">

                    <div class="col-md-12">
                        <div class="hotmeal-fancy-title">
                            <span>account</span>
                            <h2>account</h2>
                            <img src="{% static 'images/fancy-title-img.png' %}" alt="">
                        </div>
                        <div class="hotmeal-menu hotmeal-menu-list hotmeal-menu-filter hotmeal-breakfast-manu">
                            <ul class="row">
                                <li class="col-md-6 element-item desserts">
                                    <div class="hotmeal-menu-list-text">
                                        <h5><a href="{% url 'profile:register_page' %}">Edit account</a></h5>
                                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vel pharetra
                                            odio. Donec sit amet varius massa.</p>
                                    </div>
                                </li>
                                <li class="col-md-6 element-item drinks">
                                    <div class="hotmeal-menu-list-text">
                                        <h5><a href="{% url 'order:cart_page' %}">Cart user</a></h5>
                                        <p>Donec porta magna eget leo molestie, tempus consectetur erat facilisis.
                                            Suspendisse justo ante, tempus at nulla eu, </p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!--// Main Section \\-->
    </div>
    <!--// Main Content \\-->

{% endblock %}

hut_meal_profile/templates/login.html
{% extends 'base/base.html' %}
{% block contents %}
    {% load static %}

    <!--// SubHeader \\-->
    <div class="hotmeal-subheader">
        <span class="hotmeal-subheader-transparent"></span>
        <div class="hotmeal-subheader-text">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <span>Login</span>
                        <h1>Login</h1>
                        <p>Sed vulputate elementum aliquam. Nunc vel efficitur ante. Ut gravida nulla id ornare
                            sodales.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="hotmeal-breadcrumb">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <ul>
                            <li><a href="index-2.html">Homepage</a></li>
                            <li class="active">Login</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--// SubHeader \\-->

    <!--// Main Content \\-->
    <div class="hotmeal-main-content">

        <!--// Main Section \\-->
        <div class="hotmeal-main-section">
            <div class="container">
                <div class="row">

                    <div class="col-md-12">
                        <div class="hotmeal-reserve-table hotmeal-reservation-wrap">
                            <div class="hotmeal-fancy-title">
                                <span>Login</span>
                                <h2>Login user/ <a style="color: #4ac1f7" href="{% url 'profile:register_page' %}">register</a></h2>
                                <img src="images/fancy-title-img.png" alt="">
                            </div>
                            <form action="{% url 'profile:login_page' %}" method="post">
                                {% csrf_token %}
                                <ul>
                                    <li>
                                        {{ login_form.username }}
{#                                        <input type="text" value="Name*"#}
{#                                               onblur="if(this.value == '') { this.value ='Name*'; }"#}
{#                                               onfocus="if(this.value =='Name*') { this.value = ''; }">#}
                                    </li>
                                    <li>
                                        {{ login_form.password }}
{#                                        <input type="text" value="password*"#}
{#                                               onblur="if(this.value == '') { this.value ='password*'; }"#}
{#                                               onfocus="if(this.value =='password*') { this.value = ''; }">#}
                                    </li>
                                    <li><label class="submit"><input type="submit"
                                                                     value="Find Table"><span></span></label></li>
                                </ul>
                            </form>
                        </div>
                    </div>


                </div>
            </div>
        </div>
        <!--// Main Section \\-->

    </div>
    <!--// Main Content \\-->

{% endblock %}

hut_meal_profile/templates/register.html
{% extends 'base/base.html' %}
{% block contents %}
    {% load static %}


    <!--// SubHeader \\-->
    <div class="hotmeal-subheader">
        <span class="hotmeal-subheader-transparent"></span>
        <div class="hotmeal-subheader-text">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <span>Register</span>
                        <h1>Register</h1>
                        <p>Sed vulputate elementum aliquam. Nunc vel efficitur ante. Ut gravida nulla id ornare
                            sodales.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="hotmeal-breadcrumb">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <ul>
                            <li><a href="index-2.html">Homepage</a></li>
                            <li class="active">Reservation Table</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--// SubHeader \\-->

    <!--// Main Content \\-->
    <div class="hotmeal-main-content">

        <!--// Main Section \\-->
        <div class="hotmeal-main-section">
            <div class="container">
                <div class="row">

                    <div class="col-md-12">
                        <div class="hotmeal-reserve-table hotmeal-reservation-wrap">
                            <div class="hotmeal-fancy-title">
                                <span>Reservation</span>
                                {% if request.user.is_authenticated %}
                                <h2>Edit account</h2>
                                {% else %}
                                    <h2>Register user/ <a style="color: #4ac1f7"
                                                          href="{% url 'profile:login_page' %}">login</a></h2>
                                {% endif %}
                                <img src="{% static 'images/fancy-title-img.png' %}" alt="">
                            </div>
                            <form action="{% url 'profile:register_page' %}" method="post">
                                {% csrf_token %}
                                <ul>
                                    <li>{{ register_form.username }}</li>
                                    <li>{{ register_form.first_name }}</li>
                                    <li>{{ register_form.last_name }}</li>
                                    <li>{{ register_form.email }}</li>
                                    <li>{{ register_form.password }}</li>
                                    <li>{{ register_form.password2 }}</li>
                                    <li>{{ register_form.phone }}</li>
                                    <li>{{ register_form.company }}</li>
                                    <li>{{ register_form.address }}</li>
                                    <li><label class="submit"><input type="submit"
                                                                     value="Find Table"><span></span></label></li>
                                </ul>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--// Main Section \\-->

    </div>
    <!--// Main Content \\-->

{% endblock %}